INSERT INTO Score_Songs(song, score_ID, track_number)
VALUES ("Interference of Others", 24, 1),
       ("the end of midsummer", 24, 2),
       ("emergency evacuation to regression", 24, 3),
       ("false regeneration", 24, 4),
       ("substitute invasion", 24, 5),
       ("orchestral suite no. 3 in D major, Bwv bach 1068", 24, 6),
       ("The Passage of Emptiness", 24, 7),
       ("THANATOS (IF I CAN’T BE YOURS)", 24, 8),
       ("Escape to the Beginning", 24, 9),
       ("Honeymoon with Anxiety", 24, 10),
       ("Come, Sweet Death", 24, 11),
       ("Lord, Joy of Man's Desiring", 24, 12),
       ("Expansion of Blockade", 24, 13),
       ("Opening of Dream", 24, 14),
       ("Why So Serious?", 23, 1),
       ("I'm Not a Hero", 23, 2),
       ("Harvey Two-Face", 23, 3),
       ("Aggressive Expansion", 23, 4),
       ("Always a Catch", 23, 5),
       ("Blood on My Hands", 23, 6),
       ("A Little Push", 23, 7),
       ("Like a Dog Chasing Cars", 23, 8),
       ("I Am the Batman", 23, 9),
       ("And I Thought My Jokes Were Bad", 23, 10),
       ("Agent of Chaos", 23, 11),
       ("Introduce a Little Anarchy", 23, 12),
       ("Watch the World Burn", 23, 13),
       ("A Dark Knight", 23, 14),
       ("Hrakiri Theme - Original Soundtrack Theme from Harakiri", 1, 1),
       ("Annihilate", 22, 1),
       ("Am I dreaming", 22, 2),
       ("All the Way Live", 22, 3),
       ("Danger (Spider)", 22, 4),
       ("Hummingbird", 22, 5),
       ("Calling", 22, 6),
       ("Silk & Cologne", 22, 7),
       ("Link Up", 22, 8),
       ("Self Love", 22, 9),
       ("Home", 22, 10),
       ("Nonviolent Communication", 22, 11),
       ("Givin' Up (Not the One)", 22, 12),
       ("Nas Morales", 22, 13),
       ("Die Walkuere", 2, 1),
       ("Lacrimosa", 2, 2),
       ("Korobushka (Korobeyniki)", 2, 3),
       ("Im Wald im gruenen", 2, 4),
       ("Blue Danube", 2, 5),
       ("Tannhaeuser", 2, 6),
       ("MoyaMarusechka", 2, 7),
       ("Svyashchennaya Voyna (The Sacred War)", 2, 8),
       ("Rags to Riches", 21, 1),
       ("Sincerely", 21, 2),
       ("Speedo", 21, 3),
       ("Stardust", 21, 4),
       ("Look in My Eyes", 21, 5),
       ("Life Is but a Dream", 21, 6),
       ("Remeber (Walking in the Sand)", 21, 7),
       ("Baby I Love You", 21, 8),
       ("Beyond the Sea", 21, 9),
       ("Sunshine of Your Love", 21, 10),
       ("Mannish Boy", 21, 11),
       ("Layla", 21, 12),
       ("Dance of the Cuckoos", 3, 1),
       ("The Human Condition I: No Greater Love Original Soundtrack Theme", 20, 1),
       ("Title Backing (M-1-2)", 4, 1),
       ("To the Water Mill (M-2-1)", 4, 2),
       ("Samurai Search One (M-3-1)", 4, 3),
       ("Kambei and Katsushiro ~ Kikuchiyo's Mambo (M-6-2)", 4, 4),
       ("Rikichi's Tears ~ White Rice (M-7-1)", 4, 5),
       ("Samurai Search Two (M-8-2)", 4, 6),
       ("Gorobei (M-9-1)", 4, 7),
       ("Let's Do It (M-10-1)", 4, 8),
       ("A Fish That Was Caught (M-11-2)", 4, 9),
       ("Six Samurai (M-12-2)", 4, 10),
       ("Unconventional Man (M-13-2)", 4, 11),
       ("Morning of Departure (M-14-1)", 4, 12),
       ("Travel Scenery ~ Our Castle (M-15-1)", 4, 13),
       ("Wild Warrior's Coming (M-17-2)", 4, 14),
       ("Seven Men Complete (M-18-1)", 4, 15),
       ("Katsushiro and Shino (M-19·20-3)", 4, 16),
       ("Katsushiro, Returning (M-21-3)", 4, 17),
       ("Bed Change (M-22-1)", 4, 18),
       ("In the Forest of The Water God (M-23-4)", 4, 19),
       ("Barley Field (M-24-1)", 4, 20),
       ("Kambei's Anger (M-25-2)", 4, 21),
       ("Interlude (M-Interlude)", 4, 22),
       ("Harvest (M-26-1)", 4, 23),
       ("Rikichi's Conflict (M-27·28-3)", 4, 24),
       ("Heihachi and Rikichi (M-28-5)", 4, 25),
       ("Rural Landscape (M-29·30-1)", 4, 26),
       ("Wimp, Samurai's Habit (M-31-1)", 4, 27),
       ("Omen of Wild Warriors (M-32-4)", 4, 28),
       ("To the Night Attack (M-35, From Film)", 4, 29),
       ("Flag (M-39, From Film)", 4, 30),
       ("Sudden Reunion (M-40-1)", 4, 31),
       ("Magnificent Samurai (M-41-2)", 4, 32),
       ("Invisible Wild Warriors (M-43-1)", 4, 33),
       ("Kikuchiyo's Rouse (M-44-1)", 4, 34),
       ("Compensation (M-45-1)", 4, 35),
       ("Tryst (M-46-1)", 4, 36),
       ("Manzo and Shino (M-47-4, M-48)", 4, 37),
       ("Rice Planting Song (PS. From Film)", 4, 38),
       ("Ending (M-49-2)", 4, 39),
       ("A Storm Is Coming", 19, 1),
       ("Hope and Memory", 19, 2),
       ("Minas Tirith (featuring Ben Del Maestro)", 19, 3),
       ("The White Tree", 19, 4),
       ("The Steward of Gondor (featuring Billy Boyd)", 19, 5),
       ("Minas Morgul", 19, 6),
       ("The Ride of the Rohirrim", 19, 7),
       ("Twilight and Shadow (featuring Renée Fleming)", 19, 8),
       ("Cirith Ungol", 19, 9),
       ("Andúril", 19, 10),
       ("Shelob's Lair", 19, 11),
       ("Ash and Smoke", 19, 12),
       ("The Fields of the Pelennor", 19, 13),
       ("Hope Fails", 19, 14),
       ("The Black Gate Opens (featuring Sir James Galway)", 19, 15),
       ("The End of All Things (featuring Renée Fleming)", 19, 16),
       ("The Return of the King (featuring Sir James Galway, Viggo Mortensen, and Renée Fleming)", 19, 17),
       ("The Grey Havens (featuring Sir James Galway)", 19, 18),
       ("Into the West (words and music by Fran Walsh, Howard Shore and Annie Lennox; performed by Annie Lennox)", 19, 19),
       ("Main Title/The Immigrant", 5, 1),
       ("A New Carpet", 5, 2),
       ("Kay", 5, 3),
       ("Ev'ry Time I Look In Your Eyes/After the Party", 5, 4),
       ("Vito and Abbandando", 5, 5),
       ("Senza Mamma/Ciuri-Ciuri/Napule Ve Salute", 5, 6),
       ("The Godfathers at Home", 5, 7),
       ("Remember Vito Andolini", 5, 8),
       ("Michael Comes Home", 5, 9),
       ("Marcia Stilo Italiano", 5, 10),
       ("Ninna Nanna a Michele", 5, 11),
       ("The Brothers Mourn", 5, 12),
       ("The Murder of Don Fanucci", 5, 13),
       ("End Title", 5, 14),
       ("The Good, the Bad and the Ugly (main title)", 18, 1),
       ("The Sundown", 18, 2),
       ("The Strong", 18, 3),
       ("The Desert", 18, 4),
       ("The Carriage of the Spirits", 18, 5),
       ("Marcia", 18, 6),
       ("The Story of a Soldier", 18, 7),
       ("Marcia Without Hope", 18, 8),
       ("The Death of a Soldier", 18, 9),
       ("The Ecstasy of Gold", 18, 10),
       ("The Trio (main title)", 18, 11),
       ("Why So Serious?", 17, 1),
       ("Angel Baby", 17, 2),
       ("Never Be Anyone Else But You", 17, 3),
       ("Poor Little Fool", 17, 4),
       ("Don't Be Cruel", 17, 5),
       ("Are You Lonesome Tonight?", 17, 6),
       ("Near to the Hear of God/There is a Place of Quiet Rest", 17, 7),
       ("The Magic Begins", 6, 1),
       ("It's Now or Never", 6, 2),
       ("Die Forelle", 6, 3),
       ("Forellenquintett (Trout Quintet), 4th movement", 6, 4),
       ("Opening", 7, 1),
       ("Conciliation I", 7, 2),
       ("On the Way to Rich House", 7, 3),
       ("Conciliation II", 7, 4),
       ("Plum Juice", 7, 5),
       ("Mr. Yoon and Park", 7, 6),
       ("Conciliation III", 7, 7),
       ("The Belt of Faith", 7, 8),
       ("Moon Gwang Left", 7, 9),
       ("Camping", 7, 10),
       ("The Hellgate", 7, 11),
       ("Heartrending Story of Bubu", 7, 12),
       ("Zappaguri", 7, 13),
       ("Ghost", 7, 14),
       ("The Family is Busy", 7, 15),
       ("Busy to Survive", 7, 16),
       ("The Frontal Lobe of Ki Taek", 7, 17),
       ("Water, Ocean", 7, 18),
       ("Water, Ocean Again", 7, 19),
       ("It Is Sunday Morning", 7, 20),
       ("Blood and Sword", 7, 21),
       ("Yasan", 7, 22),
       ("Moving", 7, 23),
       ("Ending", 7, 24),
       ("Soju One Glass", 7, 25),
       ("Suite - Pt.1", 16, 1),
       ("Suite - Pt.2", 16, 2),
       ("Opening Credits", 16, 3),
       ("The First Castle", 16, 4),
       ("The Flute Orchestra", 16, 5),
       ("The Buddhist Praying Temple", 16, 6),
       ("Hell's Picture Scroll", 16, 7),
       ("The Crimson Citadel", 16, 8),
       ("Tsurumaru's Flute", 16, 9),
       ("Departing for the Front", 16, 10),
       ("Escape", 16, 11),
       ("Assault", 16, 12),
       ("The Battle of Yawatano", 16, 13),
       ("Lamentation", 16, 14),
       ("Flute of Darkness", 16, 15),
       ("Ending Credits", 16, 16),
       ("Burnin' and Lootin'", 15, 1),
       ("That Loving Feeling", 15, 2),
       ("More Bounce to the Ounce", 15, 3),
       ("Mon Esprit Part en Couille", 15, 4),
       ("DJ Skud Interlude", 15, 5),
       ("Wedding Songs Medley", 15, 6),
       ("Funk Funk", 15, 7),
       ("Tak Hedat", 15, 8),
       ("Outstanding", 15, 9),
       ("Loufou Lakari", 15, 10),
       ("The Beat Goes On", 15, 11),
       ("Nsangu Nsangu", 15, 12),
       ("Ellens, Gesang III", 15, 13),
       ("Hardcore", 15, 14),
       ("Groove Holmes", 15, 15),
       ("Ricky's Theme", 15, 16),
       ("Eugene's Lament", 15, 17),
       ("Main Title (The Godfather Waltz)", 8, 1),
       ("I Have But One Heart", 8, 2),
       ("The Pickup", 8, 3),
       ("Connie's Wedding", 8, 4),
       ("The Halls of Fear", 8, 5),
       ("Sicilian Pastorale", 8, 6),
       ("Love Theme from The Godfather", 8, 7),
       ("The Godfather Waltz", 8, 8),
       ("Apollonia", 8, 9),
       ("The New Godfather", 8, 10),
       ("The Baptism", 8, 11),
       ("The Godfather Finale", 8, 12),
       ("J'ai Deux Amours", 14, 1),
       ("Come On-A My House", 14, 2),
       ("Cuban Mambo", 14, 3),
       ("Gondora no uta", 14, 4),
       ("Bibbidi-Bobbidi-Boo", 14, 5),
       ("Happy Birthday", 14, 6),
       ("Too Young", 14, 7),
       ("Parade of the Tine Soldiers", 14, 8),
       ("Theme From Schindler's List", 13, 1),
       ("Jewish Town (Krakow Ghetto - Winter '41)", 13, 2),
       ("Immolation (With Our Lives, We Give Life)", 13, 3),
       ("Remembrances", 13, 4),
       ("Schindler's Workforce", 13, 5),
       ("Oyf'n Pripetshok And Nacht Aktion", 13, 6),
       ("I Could Have Done More", 13, 7),
       ("Auschwitz-Birkenau", 13, 8),
       ("Stolen Memories", 13, 9),
       ("Making The List", 13, 10),
       ("Give Me Your Names", 13, 11),
       ("Yeroushalaim Chel Zahav (Jerusalem Of Gold)", 13, 12),
       ("Remembrances (With Itzhak Perlman)", 13, 13),
       ("Theme From Schindler's List (Reprise)", 13, 14),
       ("The Human Condition III: A Soldier's Prayer - Original Soundtrack Theme", 9, 1),
       ("Alvorada (Cartola / Carlos Cachaça / Herminio B. Carvalho) – Cartola", 12, 1),
       ("Azul Da Cor Do Mar (Tim Maia) – Tim Maia", 12, 2),
       ("Dance Across the Floor (Harry Wayne Casey / Ronald Finch) – Jimmy Bo Horne", 12, 3),
       ("Get Up (I Feel Like Being a) Sex Machine (James Brown / Bobby Byrd / Ronald R. Lenhoff) – James Brown", 12, 4),
       ("Hold Back the Water (Randy Bachman / Robin Bachman / Charles Turner) – Bachman–Turner Overdrive", 12, 5),
       ("Hot Pants Road (Charles Bobbit / James Brown / St Clair Jr Pinckney) – The J.B.'s", 12, 6),
       ("Kung Fu Fighting (Carl Douglas) – Carl Douglas", 12, 7),
       ("Magrelinha (Luiz Melodia) – Luiz Melodia", 12, 8),
       ("Metamorfose Ambulante (Raul Seixas) – Raul Seixas", 12, 9),
       ("Na Rua, Na Chuva, Na Fazenda (Hyldon) – Hyldon", 12, 10),
       ("Nem Vem Que Não Tem (Carlos Imperial) – Wilson Simonal", 12, 11),
       ("O Caminho Do Bem (Sérgio / Beto / Paulo) – Tim Maia", 12, 12),
       ("Preciso Me Encontrar (Candeia) – Cartola", 12, 13),
       ("So Very Hard to Go (Emilio Castillo / Stephen M. Kupka) – Tower of Power", 12, 14),
       ("May", 10, 1),
       ("Shawshank Prison (Stoic Theme)", 10, 2),
       ("New Fish", 10, 3),
       ("Rock Hammer", 10, 4),
       ("An Inch of His Life", 10, 5),
       ("If I Didn't Care", 10, 6),
       ("Brooks was Here", 10, 7),
       ("His Judgement Cometh", 10, 8),
       ("Suds on the Roof", 10, 9),
       ("Workfield", 10, 10),
       ("Shawshank Redeption", 10, 11),
       ("Lovesick Blues", 10, 12),
       ("Elmo Blatch", 10, 13),
       ("Sisters", 10, 14),
       ("Zihuatanejo", 10, 15),
       ("The Marriage of Figaro: Duettino - Sull'aria", 10, 16),
       ("Lovely Raquel", 10, 17),
       ("And That Right Soon", 10, 18),
       ("Compass and Guns", 10, 19),
       ("So was Red", 10, 20),
       ("End Title", 10, 21),
       ("Sweetly Breathing", 11, 1),
       ("Vaga Luna, che inargenti", 11, 2),
       ("A Smile in Hand", 11, 3),
       ("Summer Time", 11, 4),
       ("All My Best", 11, 5),
       ("Cello Sonata No. 1 in F-Major, Op 5-1", 11, 6),
       ("One More Moon", 11, 7),
       ("Sonata in C-sharp Minor, Op. 27, No.2 Moonlight", 11, 8),
       ("Toccata, BWV 914", 11, 9),
       ("Ue o muite aruko", 11, 10);